/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mamamiapizzeria;

import java.awt.Color;

/**
 *
 * @author Devin Tinsley
 */
public class CreateOrder extends javax.swing.JFrame {
    public static String sErrorMessage = "";
    public static int iPrice = 14;
    /**
     * Creates new form CreateOrder
     */
    public CreateOrder() {
        initComponents();
        getContentPane().setBackground(new Color(132, 48, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCreateOrder = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPizzaBaseType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCustomPizza = new javax.swing.JButton();
        jComboBoxCrustType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPizzaSize = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotalPrice = new javax.swing.JLabel();
        jLabelUsernamePlaceholder = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxRecentOrders = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Order");

        jPanelTitle.setBackground(new java.awt.Color(173, 61, 39));
        jPanelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTitle.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 221, 14));
        jLabel1.setText("Mama-Mia Pizzeria");
        jPanelTitle.add(jLabel1);

        jPanelCreateOrder.setBackground(new java.awt.Color(173, 61, 39));
        jPanelCreateOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanelCreateOrderLayout = new java.awt.GridBagLayout();
        jPanelCreateOrderLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanelCreateOrderLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanelCreateOrder.setLayout(jPanelCreateOrderLayout);

        jLabelWelcome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(245, 221, 14));
        jLabelWelcome.setText("Welcome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelCreateOrder.add(jLabelWelcome, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 221, 14));
        jLabel2.setText("Pizza");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelCreateOrder.add(jLabel2, gridBagConstraints);

        jComboBoxPizzaBaseType.setBackground(new java.awt.Color(245, 221, 14));
        jComboBoxPizzaBaseType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxPizzaBaseType.setMaximumRowCount(6);
        jComboBoxPizzaBaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Pizza Type", "Pepperoni", "Gluten-Free - Add $1", "Cheese", "Chicken", "Hawaiian" }));
        jComboBoxPizzaBaseType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPizzaBaseTypeItemStateChanged(evt);
            }
        });
        jComboBoxPizzaBaseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPizzaBaseTypeActionPerformed(evt);
            }
        });
        jComboBoxPizzaBaseType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxPizzaBaseTypePropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCreateOrder.add(jComboBoxPizzaBaseType, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 221, 14));
        jLabel3.setText("Crust");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelCreateOrder.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 221, 14));
        jLabel4.setText("Or");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanelCreateOrder.add(jLabel4, gridBagConstraints);

        jButtonCustomPizza.setBackground(new java.awt.Color(245, 221, 14));
        jButtonCustomPizza.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCustomPizza.setText("Create Your Own");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanelCreateOrder.add(jButtonCustomPizza, gridBagConstraints);

        jComboBoxCrustType.setBackground(new java.awt.Color(245, 221, 14));
        jComboBoxCrustType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxCrustType.setMaximumRowCount(6);
        jComboBoxCrustType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Crust Type", "Pan Pizza", "Hand Tossed Pizza", "Thin and Crispy", "Stuffed Crust - Add $1", "Bacon and Cheese Stuffed Crust - Add $2" }));
        jComboBoxCrustType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCrustTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanelCreateOrder.add(jComboBoxCrustType, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 221, 14));
        jLabel5.setText("Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelCreateOrder.add(jLabel5, gridBagConstraints);

        jComboBoxPizzaSize.setBackground(new java.awt.Color(245, 221, 14));
        jComboBoxPizzaSize.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxPizzaSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Size", "Small - $14", "Medium - $15", "Large - $16" }));
        jComboBoxPizzaSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPizzaSizeItemStateChanged(evt);
            }
        });
        jComboBoxPizzaSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPizzaSizeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCreateOrder.add(jComboBoxPizzaSize, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 221, 14));
        jLabel6.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanelCreateOrder.add(jLabel6, gridBagConstraints);

        jLabelTotalPrice.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        jLabelTotalPrice.setForeground(new java.awt.Color(245, 221, 14));
        jLabelTotalPrice.setText("$" + iPrice + ".00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanelCreateOrder.add(jLabelTotalPrice, gridBagConstraints);

        jLabelUsernamePlaceholder.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        jLabelUsernamePlaceholder.setForeground(new java.awt.Color(245, 221, 14));
        jLabelUsernamePlaceholder.setText("Placeholder");
        jLabelUsernamePlaceholder.setText(Login.username);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanelCreateOrder.add(jLabelUsernamePlaceholder, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 221, 14));
        jLabel9.setText("Returning Customer?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCreateOrder.add(jLabel9, gridBagConstraints);

        jComboBoxRecentOrders.setBackground(new java.awt.Color(245, 221, 14));
        jComboBoxRecentOrders.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxRecentOrders.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a previous order", "Fill", "From", "Database" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanelCreateOrder.add(jComboBoxRecentOrders, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(245, 221, 14));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Add to Order");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanelCreateOrder.add(jButton1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPizzaBaseTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxPizzaBaseTypePropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxPizzaBaseTypePropertyChange

    private void jComboBoxPizzaBaseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPizzaBaseTypeActionPerformed
        // TODO add your handling code here:
        String sErrorMessage = "";
        //Temp iPrice
        int iTempPrice = iPrice;
    //Base Pizza type    
        if(jComboBoxPizzaBaseType.getSelectedIndex() == 2){
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //crust type check
        if(jComboBoxCrustType.getSelectedIndex() == 4) {
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        if(jComboBoxCrustType.getSelectedIndex() == 5) {
            iTempPrice += 2;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        else{
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //Size selection
        for(int i = 1; i <= 3; i++){
            if(jComboBoxPizzaSize.getSelectedIndex()== i){
                iTempPrice += (i-1);
                jLabelTotalPrice.setText("$" + iTempPrice + ".00");
            }
        }
    }//GEN-LAST:event_jComboBoxPizzaBaseTypeActionPerformed

    private void jComboBoxPizzaBaseTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPizzaBaseTypeItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxPizzaBaseTypeItemStateChanged

    private void jComboBoxPizzaSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPizzaSizeItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxPizzaSizeItemStateChanged

    private void jComboBoxPizzaSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPizzaSizeActionPerformed
        // TODO add your handling code here:
        //temp iPrice value
        int iTempPrice = iPrice;
    //Base Pizza type    
        if(jComboBoxPizzaBaseType.getSelectedIndex() == 2){
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //crust type check
        if(jComboBoxCrustType.getSelectedIndex() == 4) {
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        if(jComboBoxCrustType.getSelectedIndex() == 5) {
            iTempPrice += 2;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        else{
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //Size selection
        for(int i = 1; i <= 3; i++){
            if(jComboBoxPizzaSize.getSelectedIndex()== i){
                iTempPrice += (i-1);
                jLabelTotalPrice.setText("$" + iTempPrice + ".00");
            }
        }        
    }//GEN-LAST:event_jComboBoxPizzaSizeActionPerformed

    private void jComboBoxCrustTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCrustTypeActionPerformed
        // TODO add your handling code here:
        //temp value of iPrice
        int iTempPrice = iPrice;
    //Base Pizza type    
        if(jComboBoxPizzaBaseType.getSelectedIndex() == 2){
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //crust type check
        if(jComboBoxCrustType.getSelectedIndex() == 4) {
            iTempPrice += 1;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        if(jComboBoxCrustType.getSelectedIndex() == 5) {
            iTempPrice += 2;
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
        else{
            jLabelTotalPrice.setText("$" + iTempPrice + ".00");
        }
    //Size selection
        for(int i = 1; i <= 3; i++){
            if(jComboBoxPizzaSize.getSelectedIndex()== i){
                iTempPrice += (i-1);
                jLabelTotalPrice.setText("$" + iTempPrice + ".00");
            }
        }
    }//GEN-LAST:event_jComboBoxCrustTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCustomPizza;
    private javax.swing.JComboBox jComboBoxCrustType;
    private javax.swing.JComboBox jComboBoxPizzaBaseType;
    private javax.swing.JComboBox jComboBoxPizzaSize;
    private javax.swing.JComboBox jComboBoxRecentOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTotalPrice;
    private javax.swing.JLabel jLabelUsernamePlaceholder;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelCreateOrder;
    private javax.swing.JPanel jPanelTitle;
    // End of variables declaration//GEN-END:variables
}
